config/routes.rb
Rails.application.routes.draw do
  root "activities#index"

  resources :activities
  resources :types
  resources :subjects
end

app/models/activity.rb
class Activity < ApplicationRecord
    belongs_to :type
    has_and_belongs_to_many :subjects

    validates :date, presence: true
    validates :link, presence: true
    validates :duration, presence: true, numericality: {only_integer: true }
    validates :comment, presence: true

    def print_subjects()
        s = ""
        subjects.each do |subject|
            s += "#{subject.name}, "
        end
        if(s != "")
            s = s[0..-3]
        end
        return s
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_and_belongs_to_many :activities

    validates :name, presence: true
end

app/models/type.rb
class Type < ApplicationRecord
    has_many :activities

    validates :name, presence: true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities = Activity.all
  end

  def show
    @activity = Activity.find(params[:id])
  end

  def new
    @activity = Activity.new
  end 

  def create
    @activity = Activity.new(activity_params)
    
    if @activity.save
      @subjects = Subject.where(:id => params[:subjects_id])
      @activity.subjects << @subjects 
      redirect_to @activity
    else
      render :new
    end
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def update
    @activity = Activity.find(params[:id])

    if @activity.update(activity_params)
      @subjects = Subject.where(:id => params[:subjects_id])
      @activity.subjects.clear
      @activity.subjects << @subjects 
      redirect_to @activity
    else
      render :edit
    end
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy

    redirect_to root_path
  end 

  private
    def activity_params
      params.require(:activity).permit(:date, :subjects_id, :type_id, :link, :duration, :comment)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
    @subjects = Subject.all
  end
    
  def show
    @subject = Subject.find(params[:id])
  end
    
  def new
    @subject = Subject.new
  end
    
  def create
    @subject = Subject.new(subject_params)
      
    if @subject.save
      redirect_to @subject
    else
      render :new
    end
  end
    
  def edit
    @subject = Subject.find(params[:id])
  end
    
  def update
    @subject = Subject.find(params[:id])
      
    if @subject.update(subject_params)
      redirect_to @subject
    else
      render :edit
    end
  end
    
  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    
    redirect_to root_path
  end
    
  private
    def subject_params
      params.require(:subject).permit(:name)
    end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  def index
    @types = Type.all
  end
    
  def show
    @type = Type.find(params[:id])
  end
    
  def new
    @type = Type.new
  end
    
  def create
    @type = Type.new(type_params)
      
    if @type.save
      redirect_to @type
    else
      render :new
    end
  end
    
  def edit
    @type = Type.find(params[:id])
  end
    
  def update
    @type = Type.find(params[:id])
      
    if @type.update(type_params)
      redirect_to @type
    else
      render :edit
    end
  end
    
  def destroy
    @type = Type.find(params[:id])
    @type.destroy
    
    redirect_to root_path
  end
    
  private
    def type_params
      params.require(:type).permit(:name)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/activities/_form.html.erb
<%= form_with model: activity do |form| %>
  <div>
    <%= form.label :date %><br>
    <%= form.date_field :date %>
    <% activity.errors.full_messages_for(:date).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :type %><br>
    <%= form.select :type_id, Type.all.collect { |t| [ t.name, t.id] } %>
    <% activity.errors.full_messages_for(:type_id).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :subjects %><br>
    <%= select_tag :subjects_id, options_for_select(Subject.all.collect { |s| [s.name, s.id] }, 
      activity.subjects.collect { |s| s.id}), {:multiple=>true}%>
    <% activity.errors.full_messages_for(:subjects).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :link %><br>
    <%= form.text_field :link %>
    <% activity.errors.full_messages_for(:link).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :duration %><br>
    <%= form.number_field :duration %>
    <% activity.errors.full_messages_for(:duration).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :commment %><br>
    <%= form.text_area :comment %>
    <% activity.errors.full_messages_for(:commment).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Edit Activity</h1>

<%= render "form", activity: @activity %>

app/views/activities/index.html.erb
<h1>Activities</h1>

<ul>
  <% @activities.each do |activity| %>
    <li>
        <%= link_to activity.date, activity %>
        <%= activity.type.name %>
        <%= activity.print_subjects %>
        <%= activity.duration %>
        <%= activity.comment %>
    </li>
  <% end %>
</ul>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render "form", activity: @activity %>

app/views/activities/show.html.erb
<h1><%= @activity.date %></h1>

<% @activity.subjects.each do |s| %>
	<p><%= s.name %> </p>

<% end %>

<p><%= @activity.type.name %></p>
<p><%= @activity.link %></p>
<p><%= @activity.duration %></p>
<p><%= @activity.comment %></p>

<ul>
    <li><%= link_to "Edit", edit_activity_path(@activity) %></li>
    <li><%= link_to "Destroy", activity_path(@activity), method: :delete,
        data: { confirm: "Are you sure?" } %>
    </li>
</ul>

app/views/layouts/_navbar.html.erb
<header>
    <div class='container'>
        <nav>
            <ul>
                <li><%= link_to "Activity", activities_path%></li>
                <li><%= link_to "New Activity", new_activity_path%></li>
                <li><%= link_to "New Type", new_type_path%></li>
                <li><%= link_to "New Subject", new_subject_path%></li>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proglog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/subjects/_form.html.erb
<%= form_with model: subject do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% subject.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Edit Subject</h1>

<%= render "form", subject: @subject %>

app/views/subjects/index.html.erb
<h1>Subjects#index</h1>
<p>Find me in app/views/subjects/index.html.erb</p>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render "form", subject: @subject %>

app/views/subjects/show.html.erb
<h1><%= @subject.name %></h1>

<ul>
    <li><%= link_to "Edit", edit_subject_path(@subject) %></li>
    <li><%= link_to "Destroy", subject_path(@subject), method: :delete,
        data: { confirm: "Are you sure?" } %>
    </li>
</ul>

app/views/types/_form.html.erb
<%= form_with model: type do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% type.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Edit Type</h1>

<%= render "form", type: @type %>

app/views/types/index.html.erb
<h1>Types</h1>

app/views/types/new.html.erb
<h1>New Type</h1>

<%= render "form", type: @type %>

app/views/types/show.html.erb
<h1><%= @type.name %></h1>

<ul>
    <li><%= link_to "Edit", edit_type_path(@type) %></li>
    <li><%= link_to "Destroy", type_path(@type), method: :delete,
        data: { confirm: "Are you sure?" } %>
    </li>
</ul>